export default{
	sideBarACtive: false,
	showPreloader: false,
	limitedObjects: 0,
	raions: [],
	objects: [],
	districts: [],
	current_object: {},
	user: null,
	object_id: null,
	availabledevices: [],
	sensors: [],
	setMarker: false,
	markerObj: {},
	unreglamentedDevices: [],
	users:[],
	indexLoadres:{
        monitoringObjectsLoading:true,
        limitedObjectsLoading:true,
        unreglamentedDevicesLoading:true,
        unreglamentedObjectsLoading:true,
	},
}